flaskblog/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo
from wtforms.widgets import TextArea


class NewPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = StringField('Content', validators=[
                          DataRequired()], widget=TextArea())
    submit = SubmitField('Create')


class UpdatePostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = StringField('Content', validators=[
                          DataRequired()], widget=TextArea())
    submit = SubmitField('Update')

flaskblog/post/routes.py
from flaskblog import db
from flask_login import login_required, current_user, logout_user, login_user, login_required
from secrets import token_hex
from flaskblog.post.forms import NewPostForm, UpdatePostForm
from flask import redirect, render_template, flash, request, url_for, Blueprint
from flaskblog.models import Post, User
import bcrypt


post = Blueprint('post', __name__)


@ post.route('/post/create', methods=['GET', 'POST'])
@ login_required
def create_post():
    form = NewPostForm()
    title, content = form.title.data, form.content.data
    if form.validate_on_submit():
        new_post = Post(title=title, content=content,
                        user_id=current_user.id)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for('main.home'))

    return render_template('create_post.html', title='Create A New Post', form=form)


@ post.route('/post/<id>', methods=['GET', 'POST'])
def get_post(id):
    post = Post.query.get(id)
    return render_template('post.html', title=post.title, post=post)


@ post.route('/post/update/<id>', methods=['GET', 'POST', 'DELETE'])
@ login_required
def update_post(id):
    post = Post.query.get(id)
    form = UpdatePostForm()
    delete_form = DeletePostForm()

    title, content = form.title.data, form.content.data

    if request.method == 'POST':
        post.title = title
        post.content = content
        db.session.commit()
        flash('Successfully Updated Your Post')
        return redirect(f'/post/update/{id}')

    form.title.data = post.title
    form.content.data = post.content
    return render_template('update_post.html', title=post.title, post=post, form=form)


@ post.route("/post/delete")
@ login_required
def delete_post():
    id = request.args.get("id")
    post = Post.query.get(id)

    if current_user.id == post.author.id:
        db.session.delete(post)
        db.session.commit()
        return redirect(url_for('main.home'))

    return 'Error', 403

flaskblog/templates/account.html
{% extends "base.html" %} {% block content %}
<h2 class="sm:text-4xl my-2 text-3xl leading-tight font-semibold">
    Welcome <span class="text-indigo-500">{{current_user.name}}</span>
</h2>
<figure class="bg-gray-100 rounded-xl p-8">
    <img
        class="w-32 h-32 rounded-full"
        src="{{image_file}}"
        alt=""
        width="384"
        height="512"
    />
    <div class="pt-6 te space-y-4">
        <!-- <blockquote>
            <p class="text-lg font-semibold">
                “Tailwind CSS is the only framework that I've seen scale on
                large teams. It’s easy to customize, adapts to any design, and
                the build size is tiny.”
            </p>
        </blockquote> -->
        <figcaption class="font-medium">
            <div class="text-cyan-600">{{current_user.name}}</div>
            <div class="text-gray-500">{{current_user.email}}</div>
        </figcaption>
    </div>
    <div class="w-full">
        <h2 class="my-4 text-2xl font-semibold tracking-tight">Account Info</h2>
        <form
            class="bg-white shadow-md rounded px-8 pt-6 pb-8 my-4"
            method="POST"
            action=""
            enctype="multipart/form-data"
        >
            {{form.hidden_tag()}}
            <div class="mb-4">
                {{form.name.label(class="block text-gray-700 text-sm font-bold
                mb-2", for="name")}} {{form.name(class="shadow appearance-none
                border rounded w-full py-2 px-3 text-gray-700 leading-tight
                focus:outline-none focus:shadow-outline", id="name",
                placeholder="Username")}} {% if form.name.errors %} {% for error
                in form.name.errors %}
                <p class="text-red-500 text-xs italic">{{error}}</p>
                {% endfor %} {% endif %}
            </div>
            <div class="mb-4">
                {{form.email.label(class="block text-gray-700 text-sm font-bold
                mb-2", for="email")}} {{form.email(class="shadow appearance-none
                border rounded w-full py-2 px-3 text-gray-700 leading-tight
                focus:outline-none focus:shadow-outline", id="email",
                placeholder="Email")}} {% if form.email.errors %} {% for error
                in form.email.errors %}
                <p class="text-red-500 text-xs italic">{{error}}</p>
                {% endfor %} {% endif %}
            </div>

            <div class="mb-4">
                {{form.picture.label(class="block text-gray-700 text-sm
                font-bold mb-2", for="email")}} {{form.picture(class="shadow
                appearance-none border rounded w-full py-2 px-3 text-gray-700
                leading-tight focus:outline-none focus:shadow-outline",
                id="email", placeholder="Email")}} {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <p class="text-red-500 text-xs italic">{{error}}</p>
                {% endfor %} {% endif %}
            </div>

            <div class="flex items-center justify-between">
                {{form.submit(class="bg-blue-500 hover:bg-blue-700 text-white
                font-bold py-2 px-4 rounded focus:outline-none
                focus:shadow-outline")}}
                <!-- <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
        Forgot Password?
      </a> -->
            </div>
        </form>
        <p class="text-center text-gray-500 text-xs">
            &copy;2020 Flask Blog Corp. All rights reserved.
        </p>
    </div>
</figure>

{% endblock %}

flaskblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
            rel="apple-touch-icon"
            sizes="48x48"
            href="static/maskable_icon_x48.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="72x72"
            href="static/maskable_icon_x72.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="96x96"
            href="static/maskable_icon_x96.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="128x128"
            href="static/maskable_icon_x128.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="192x192"
            href="static/maskable_icon_x192.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="384x384"
            href="static/maskable_icon_x384.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="512x512"
            href="static/maskable_icon_x512.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="57x57"
            href="static/apple-icon-57x57.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="60x60"
            href="static/apple-icon-60x60.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="72x72"
            href="static/apple-icon-72x72.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="76x76"
            href="static/apple-icon-76x76.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="114x114"
            href="static/apple-icon-114x114.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="120x120"
            href="static/apple-icon-120x120.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="144x144"
            href="static/apple-icon-144x144.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="152x152"
            href="static/apple-icon-152x152.png"
        />
        <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="static/apple-icon-180x180.png"
        />
        <link
            rel="icon"
            type="image/png"
            sizes="192x192"
            href="static/android-icon-192x192.png"
        />
        <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="static/favicon-32x32.png"
        />
        <link
            rel="icon"
            type="image/png"
            sizes="96x96"
            href="static/favicon-96x96.png"
        />
        <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="static/favicon-16x16.png"
        />
        <link rel="manifest" href="static/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta
            name="msapplication-TileImage"
            content="static/ms-icon-144x144.png"
        />
        <meta name="theme-color" content="#3f51b5" />
        <title>{{title}}</title>
        {% block head %} {% endblock %}
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.4/tailwind.min.css"
            integrity="sha512-paVHVRRhdoOu1nOXKnqDC1Vka0nh7FAmU3nsM4n2FKxOQTeF6crMdMfkVvEsuaOXZ6oEAVL5+wLbQcule/Xdag=="
            crossorigin="anonymous"
        />
    </head>
    <body class="p-0">
        <header>
            <div class="px-3 py-2 bg-indigo-500 text-gray-100">
                <div
                    class="flex p-3 font-semibold text-lg space-x-2 sm:space-x-none w-auto container mx-auto"
                >
                    <div class="mr-auto">
                        <a
                            href="{{ url_for('main.home') }}"
                            class="hover:text-gray-400 transition-all active:text-gray-600"
                            >Flask Blog</a
                        >
                    </div>
                    <ul class="list-none flex justify-end space-x-5">
                        {% if current_user.is_authenticated %}
                        <li>
                            <a
                                href="{{ url_for('post.create_post') }}"
                                class="hover:text-gray-400 transition-all active:text-gray-600"
                                >Create</a
                            >
                        </li>
                        <li>
                            <a
                                href="/user/{{current_user.id}}"
                                class="hover:text-gray-400 transition-all active:text-gray-600"
                                >Account</a
                            >
                        </li>
                        <li>
                            <a
                                href="{{ url_for('auth.logout') }}"
                                class="hover:text-gray-400 transition-all active:text-gray-600"
                                >Logout</a
                            >
                        </li>
                        {% else %}
                        <li>
                            <a
                                href="{{ url_for('auth.login') }}"
                                class="hover:text-gray-400 transition-all active:text-gray-600"
                                >Login</a
                            >
                        </li>
                        <li>
                            <a
                                href="{{ url_for('auth.register') }}"
                                class="hover:text-gray-400 transition-all active:text-gray-600"
                                >Register</a
                            >
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </header>
        <main class="">
            <div class="container m-auto px-3 py-2">
                {% with messages = get_flashed_messages() %} {% if messages %}
                {% for message in messages%}
                <div
                    class="bg-gray-300 text-sm p-1 font-semibold tracking-wide"
                >
                    {{ message }}
                </div>
                {% endfor %} {% endif %} {%endwith %} {% block content %} {%
                endblock %}
            </div>
        </main>

        <!-- <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"
        ></script> -->
        <script src="{{url_for('static', filename='index.js')}}"></script>
    </body>
</html>

flaskblog/templates/create_post.html
{% extends "base.html" %} {% block content %}
<div class="w-full">
    <h2 class="my-4 text-2xl font-semibold tracking-tight">{{title}}</h2>
    <form
        class="bg-white shadow-md rounded px-8 pt-6 pb-8 my-4"
        method="POST"
        action=""
        enctype="multipart/form-data"
    >
        {{form.hidden_tag()}}
        <div class="mb-4">
            {{form.title.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="name")}} {{form.title(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline", id="name",
            placeholder="Add a catchy title...")}} {% if form.title.errors %} {%
            for error in form.title.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>
        <div class="mb-4">
            {{form.content.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="email")}} {{form.content(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline h-72", id="email",
            placeholder="Whats in your mind?")}} {% if form.content.errors %} {%
            for error in form.content.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>

        <div class="flex items-center justify-between">
            {{form.submit(class="bg-blue-500 hover:bg-blue-700 text-white
            font-bold py-2 px-4 rounded focus:outline-none
            focus:shadow-outline")}}
            <!-- <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
        Forgot Password?
      </a> -->
        </div>
    </form>
    <p class="text-center text-gray-500 text-xs">
        &copy;2020 Flask Blog Corp. All rights reserved.
    </p>
</div>
{% endblock %}

flaskblog/templates/email.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{{title}}</title>
        {% block head %} {% endblock %}
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.4/tailwind.min.css"
            integrity="sha512-paVHVRRhdoOu1nOXKnqDC1Vka0nh7FAmU3nsM4n2FKxOQTeF6crMdMfkVvEsuaOXZ6oEAVL5+wLbQcule/Xdag=="
            crossorigin="anonymous"
        />
    </head>
    <body>
        <div class="text-gray-700">
            <h1 class="text-3xl font-semibold tracking-right mb-4">
                Password Update Request
            </h1>
            <p class="text-xs">
                Hey! {{user.name}},<br />
                You requested to update your password for your FlaskBlog
                account. Click the link below to reset:
            </p>
            <a
                href="{{reset_url}}"
                class="hover:text-indigo-500 transition-color duration-75 hover:underline"
            >
                Reset Password
            </a>
            <p class="text-xs">
                If you have not requested the reset, please ignore....
            </p>
        </div>
    </body>
</html>

flaskblog/templates/home.html
{% extends "base.html" %} {% block content %}

<!-- <h1 class="text-3xl font-semibold tracking-right mb-4">{{ title }}</h1> -->
<!-- <h2 class="text-3xl tracking-tight mb-4">Testing flask templating.....</h2> -->

<div class="grid tracking-tight gap-4">
    {% if posts %} {% for post in posts.items %}
    <div
        class="rounded-md px-4 pt-4 pb-10 cursor-pointer post hover:bg-gray-100 transition-color duration-75"
        data-location="/post/{{post.id}}"
    >
        <div class="border-b border-gray-400 py-1">
            <p class="text-xs">
                By
                <a
                    href="user/profile/{{post.author.id}}"
                    class="text-indigo-500 font-medium tracking-tight text-lg"
                    >@{{post.author.name}}</a
                >
                on {{post.date_posted}}
            </p>
        </div>
        <a
            href="/post/{{post.id}}"
            class="hover:text-indigo-500 transition-color duration-75 hover:underline"
        >
            <h2 class="sm:text-4xl my-2 text-3xl leading-tight font-semibold">
                {{post.title[:50]}}
            </h2>
        </a>

        <p class="leading-tight">{{post.content[:100]}}...</p>
    </div>
    {% endfor %} {% else %}
    <h2 class="text-2xl font-semibold tracking-tight">Oh no! No posts yet</h2>
    {% endif %}
</div>
<div class="space-x-1 my-4 flex justify-center">
    {% for i in posts.iter_pages(left_edge=1 , right_edge=1, left_current=1,
    right_current=1) %} {% if i %} {% if posts.page == i %}
    <a href="/?page={{i}}" class="p-1 bg-indigo-300">{{i}}</a>
    {% else %}
    <a href="/?page={{i}}" class="p-1 bg-gray-200">{{i}}</a>
    {% endif %} {% else %} ... {% endif %} {% endfor %}
</div>
{% endblock %}

flaskblog/templates/login.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-xs m-auto">
    <h2
        class="mb-4 text-align-center text-2xl font-semibold tracking-tight text-center"
    >
        Sign In to your account
    </h2>
    <form
        class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
        method="POST"
        action=""
    >
        {{form.hidden_tag()}}
        <div class="mb-4">
            {{form.email.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="email")}} {{form.email(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline", id="email",
            placeholder="Email")}} {% if form.email.errors %} {% for error in
            form.email.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>
        <div class="mb-4">
            {{form.password.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="password")}} {{form.password(class="shadow
            appearance-none border rounded w-full py-2 px-3 text-gray-700
            leading-tight focus:outline-none focus:shadow-outline",
            id="password", placeholder="Password")}} {% if form.password.errors
            %} {% for error in form.password.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>

        <div class="mb-6">
            {{form.remember(class="shadow border rounded p-2 text-gray-700
            border-gray-200 outline-none leading-tight focus:outline-none
            focus:shadow-outline", id="Remember_Me", placeholder="Remember
            Me")}} {{form.remember.label(class="text-sm font-semibold")}}

            <!-- <input class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
       -->
        </div>
        <div class="flex items-center justify-between">
            {{form.submit(class="bg-blue-500 hover:bg-blue-700 text-white
            font-bold py-2 px-4 rounded focus:outline-none
            focus:shadow-outline")}}
            <a
                href="{{url_for('main.reset_request')}}"
                class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800"
                href="#"
            >
                Forgot Password?
            </a>
        </div>
    </form>
    <p class="text-center text-gray-500 text-xs">
        &copy;2020 Flask Blog Corp. All rights reserved.
    </p>
</div>
{% endblock %}

flaskblog/templates/post.html
{% extends "base.html" %} {% block content %}
<article class="w-full">
    {% if post.author.id == current_user.id%}
    <div class="my-4">
        <a
            href="/post/update/{{post.id}}"
            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            >Update/Delete</a
        >
    </div>
    {% endif %}
    <div class="mb-4">
        <h2 class="sm:text-4xl mt-2 text-3xl leading-tight font-semibold">
            {{post.title}}
        </h2>
        <a
            href="/user/profile/{{post.author.id}} "
            class="text-indigo-500 font-medium tracking-tight text-lg"
            >@{{post.author.name}}</a
        >
    </div>
    <div class="leading-tight">{{post.content}}</div>
</article>
{% endblock %}

flaskblog/templates/posts.html
{% extends "base.html" %} {% block content %}

<h1 class="text-3xl mb-5 font-semibold tracking-tight">Here are the posts</h1>
<div class="grid tracking-tight gap-4">
    {% if posts %} {% for post in posts %}
    <div class="rounded-md px-4 pt-4 pb-10 bg-gray-300">
        <div class="border-b border-gray-400 py-1">
            <p>By {{post.author.name}} on {{post.date_posted}}</p>
        </div>
        <h2 class="text-4xl mb-1">{{post.title}}</h2>
        <p>{{post.content}}</p>
    </div>
    {% endfor %} {% else %}
    <h2 class="text-2xl font-semibold tracking-tight">Oh no! No posts yet</h2>
    {% endif %}
</div>

{% endblock %}

flaskblog/templates/register.html
{% extends "base.html" %} {% block content %}
<div class="w-full max-w-xs m-auto">
    <h2
        class="mb-4 text-align-center text-2xl font-semibold tracking-tight text-center"
    >
        Register Today
    </h2>
    <form
        class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
        method="POST"
        action=""
    >
        {{form.hidden_tag()}}
        <div class="mb-4">
            {{form.name.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="name")}} {{form.name(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline", id="name",
            placeholder="Username")}} {% if form.name.errors %} {% for error in
            form.name.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>
        <div class="mb-4">
            {{form.email.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="email")}} {{form.email(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline", id="email",
            placeholder="Email")}} {% if form.email.errors %} {% for error in
            form.email.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>
        <div class="mb-4">
            {{form.password.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="password")}} {{form.password(class="shadow
            appearance-none border rounded w-full py-2 px-3 text-gray-700
            leading-tight focus:outline-none focus:shadow-outline",
            id="password", placeholder="Password")}} {% if form.password.errors
            %} {% for error in form.password.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>

        <div class="mb-6">
            {{form.confirm_password.label(class="block text-gray-700 text-sm
            font-bold mb-2", for="confirm_password")}}
            {{form.confirm_password(class="shadow appearance-none border rounded
            w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none
            focus:shadow-outline", id="confirm_password", placeholder="Confirm
            Password")}} {% if form.confirm_password.errors %} {% for error in
            form.confirm_password.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}

            <!-- <input class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="******************">
       -->
        </div>
        <div class="flex items-center justify-between">
            {{form.submit(class="bg-blue-500 hover:bg-blue-700 text-white
            font-bold py-2 px-4 rounded focus:outline-none
            focus:shadow-outline")}}
            <!-- <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
        Forgot Password?
      </a> -->
        </div>
    </form>
    <p class="text-center text-gray-500 text-xs">
        &copy;2020 Flask Blog Corp. All rights reserved.
    </p>
</div>
{% endblock %}

flaskblog/templates/reset_request.html
{% extends "base.html" %} {% block content %}
<form action="" method="POST">
    {{form.hidden_tag()}}
    <div class="mb-4">
        {{form.email.label(class="block text-gray-700 text-sm font-bold mb-2",
        for="name")}} {{form.email(class="shadow appearance-none border rounded
        w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none
        focus:shadow-outline", id="name", placeholder="Enter your email...")}}
        {% if form.email.errors %} {% for error in form.email.errors %}
        <p class="text-red-500 text-xs italic">{{error}}</p>
        {% endfor %} {% endif %}
    </div>
    {{ form.submit(class="bg-blue-500 hover:bg-blue-700 text-white font-bold
    py-2 px-4 rounded focus:outline-none focus:shadow-outline") }}
</form>
{% endblock %}

flaskblog/templates/reset_token.html
{% extends "base.html" %} {% block content %}
<form action="" method="POST">
    {{form.hidden_tag()}}
    <div class="mb-4">
        {{form.password.label(class="block text-gray-700 text-sm font-bold
        mb-2", for="name")}} {{form.password(class="shadow appearance-none
        border rounded w-full py-2 px-3 text-gray-700 leading-tight
        focus:outline-none focus:shadow-outline", id="name", placeholder="Enter
        new Password...")}} {% if form.password.errors %} {% for error in
        form.password.errors %}
        <p class="text-red-500 text-xs italic">{{error}}</p>
        {% endfor %} {% endif %}
    </div>
    <div class="mb-4">
        {{form.confirm_password.label(class="block text-gray-700 text-sm
        font-bold mb-2", for="name")}} {{form.confirm_password(class="shadow
        appearance-none border rounded w-full py-2 px-3 text-gray-700
        leading-tight focus:outline-none focus:shadow-outline", id="name",
        placeholder="COnfrim new password...")}} {% if
        form.confirm_password.errors %} {% for error in
        form.confirm_password.errors %}
        <p class="text-red-500 text-xs italic">{{error}}</p>
        {% endfor %} {% endif %}
    </div>
    {{ form.submit(class="bg-blue-500 hover:bg-blue-700 text-white font-bold
    py-2 px-4 rounded focus:outline-none focus:shadow-outline") }}
</form>
{% endblock %}

flaskblog/templates/update_post.html
{% extends "base.html" %} {% block content %}
<div class="w-full">
    <h2 class="my-4 text-2xl font-semibold tracking-tight">{{title}}</h2>
    <form
        class="bg-white shadow-md rounded px-8 pt-6 pb-8 my-4"
        method="POST"
        action=""
        enctype="multipart/form-data"
    >
        {{form.hidden_tag()}}
        <div class="mb-4">
            {{form.title.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="name")}} {{form.title(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline", id="name",
            placeholder="Add a catchy title...")}} {% if form.title.errors %} {%
            for error in form.title.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>
        <div class="mb-4">
            {{form.content.label(class="block text-gray-700 text-sm font-bold
            mb-2", for="email")}} {{form.content(class="shadow appearance-none
            border rounded w-full py-2 px-3 text-gray-700 leading-tight
            focus:outline-none focus:shadow-outline h-72", id="email",
            placeholder="Whats in your mind?")}} {% if form.content.errors %} {%
            for error in form.content.errors %}
            <p class="text-red-500 text-xs italic">{{error}}</p>
            {% endfor %} {% endif %}
        </div>

        <div class="flex items-center space-x-1">
            {{form.submit(class="bg-blue-500 hover:bg-blue-700 text-white
            font-bold py-2 px-4 rounded focus:outline-none
            focus:shadow-outline")}}
            <!-- <a class="inline-block align-baseline font-bold text-sm text-blue-500 hover:text-blue-800" href="#">
        Forgot Password?
      </a> -->
        </div>
    </form>
    <a
        href="/post/delete?id={{post.id}}"
        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
    >
        Delete
    </a>
    <p class="text-center text-gray-500 text-xs">
        &copy;2020 Flask Blog Corp. All rights reserved.
    </p>
</div>
{% endblock %}